### ISSUE TITLE
Stop polluting peoples npm install logs.

### ISSUE THREAD

**Issue by gloryknight** [opencollective/opencollective-postinstall#21]
The postinstall messages are opt-out option which is absolutely wrong. Output produced by this script is an unwanted (uninvited) message which usually called SPAM. This behavior is not GDPR compliant.
Opt-in option would mean that an admin should setup a variable to receive the output. This option would be GDPR compliant.
I am sure you would like to avoid a GDPR complain against Opencollective.

**Comment by znarf** [comment]
This package is just a tool that is made available to maintainers. It's their decision to add that to their package or not. Also, most of the time, the messages are generated by something else than the present tool.

There is effectively a discussion in the community about this practice, seems most users effectively don't like it. However, many Open Source maintainers feels it's necessary to create awareness about their fundraising strategy.

I personally feel there is currently a momentum to create a replacement for these post-install messages, see latest discussion here: https://github.com/npm/cli/pull/187. The Open Collective team see these discussions and ideas very favorably.

As for the GDPR aspect of it, I think you have a misunderstanding of what is GDPR, I invite you to read more about it: https://en.wikipedia.org/wiki/General_Data_Protection_Regulation Basically, it's about the protection of personal data, nothing else.

In the end, this is a problem that needs to be solved by the community as a whole. Open Collective is just an humble member of the community and we're looking forward to implement and support replacements to these post-install messages when they will exists.

**Comment by gloryknight** [comment]
Thank you for the fast reply. I'm glad that there is awareness and support to stop this misbehavior.
You are right, if we consider this repository on it's own as a tool made available to developers than it is not a GDPG related issue, but if one considers this repository as a part of Open Collective business model than the situation might look totally different. I do not want to start a legal battle here but to warn you about possible consequences.
The fact remains: the messages are a form of SPAM. If you do not wish to remove them willingly then the community will help you, one or another way, to correct your mistake.

**Comment by znarf** [comment]
I don't see any new point in your answer, so I'm closing the issue.

Feel free to engage in the community if you have any ideas on how to solve this aspect of open source sustainability.

I'm personally not a fan of these `postinstall` messages, and I hope we'll find a better solution in the close future.

Final note: I noticed your issue on https://github.com/maticzav/graphql-shield/issues/464. This is one example where the package maintainer is not even using the `opencollective-postinstall` tool. Also, saying Open Collective is a "suspicious organization (involved in) criminal activity" is a serious claim to make. I invite you to document you more on the subject. Happy to answer at support@opencollective.com if you have any question.
