### ISSUE TITLE
Consider adding an env flag to disable messages

### ISSUE THREAD

**Issue by moltar** [opencollective/opencollective-postinstall#8]
Annoying to see pollution in the CI logs. Eventually people will develop blindness to these messages anyways and they will completely lose effectiveness.

**Comment by eddiemonge** [comment]
Instead of a flag (or in addition) this should obey npm's loglevel
```
if (["silent", "error", "warn"].indexOf(process.env.npm_config_loglevel) < 0) {
  showPostInstall();
}
```
