### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by mostlyharmless2024** [opencollective/opencollective-postinstall#81]
Well I'm stumped... four days of banging my head on my desk is my limit...

**We can't build / deploy our application because of this package / dependency**

`sh: 1: opencollective-postinstall: Permission denied
npm ERR! code ELIFECYCLE
npm ERR! errno 126
npm ERR! inferno@7.4.8 postinstall: `opencollective-postinstall`
npm ERR! Exit status 126
npm ERR!
npm ERR! Failed at the inferno@7.4.8 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

It's a dependency of [Inferno (a](https://www.npmjs.com/package/inferno) which is a dependency of https://www.npmjs.com/package/@builder.io/widgets

We're using this inside of a Meteor 2.6 application ( https://www.meteor.com/ ) ... I'm deploying from an up-to-date windows 11 environment (though the build error occurs on the server)

Perhaps it's related to a +x (executable) permission flag that's lost between Windows / Linux?

Things I've tried:
- Directly installing various versions of `inferno` and `opencollective-postinstall` as direct dependencies
- The "DISABLE_OPENCOLLECTIVE=true" env var
- A new base docker image (applying the former var)
- A dozen other things per various GH / SO recommendations... 

Similar issues (with no solutions):
https://github.com/opencollective/opencollective-postinstall/issues/15
https://github.com/infernojs/inferno/issues/1353
https://unix.stackexchange.com/questions/610638/i-am-getting-this-error-when-i-am-trying-to-deploy-to-heroku

Any ideas?

**Comment by joonass-visma** [comment]
@brendonlamb We're facing the same issue. Did you ever figure out a workaround for this?

**Comment by ridersshare** [comment]
@joonass-visma Sorry I never reported back here, ultimately this was fixed by a patch released in Meteor version 2.6.1 by @renanccastro here: https://github.com/meteor/meteor/pull/11932

**Comment by brendonlamb** [comment]
@joonass-visma Sorry I never reported back here, ultimately this was fixed by a patch released in Meteor version 2.6.1 by @renanccastro here: meteor/meteor#11932

**Comment by mostlyharmless2024** [comment]
@joonass-visma Sorry I never reported back here, ultimately this was fixed by a patch released in Meteor version 2.6.1 by @renanccastro here: meteor/meteor#11932
